name: Scaffold Check

on: [pull_request]

jobs:
  check_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Docs
        run: |
          for file in README.md USER_MANUAL.md DESIGN_GUIDE.md flow_state.json; do
            if ! [ -f "$file" ]; then
              echo "❌ Missing $file"; exit 1
            fi
          done
